# NET Core
# Build and test NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - 'master'
    - 'refs/tags/*'

jobs:
  - job: 'Build'

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: 'Meowtrix.PixivApi.sln'
      buildConfiguration: 'Release'
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        isTag: true
        tagVersion: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]
      ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
        isTag: false
        tagVersion: 0.0.0-alpha

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) -warnAsError /p:Version=$(tagVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Pack'
      inputs:
        command: 'pack'
        packagesToPack: 'Source/Meowtrix.PixivApi/Meowtrix.PixivApi.csproj'
        includesymbols: true
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'tagVersion'

    - task: DotNetCoreCLI@2
      displayName: 'Publish to NuGet'
      condition: and(succeeded(), eq(variables.IsTag, true))
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'NuGet push feed'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Packages'
        publishLocation: 'Container'
